default:
  tags:
  - docker-images

image: nixpkgs/nix-flakes:latest

check syntax:
  stage: build
  script:
  - nix-shell -p nixpkgs-fmt --run "nixpkgs-fmt --check ."

build burpsuite-pro:
  stage: build
  script:
  - nix build .#burpsuite-pro -o burpsuite-pro

check failbowl:
  stage: build
  script:
  - nix eval .#nixosConfigurations.failbowl.config.system.build.toplevel.drvPath
